name: firebloc_functions
description: Cloud functions of FireBLoC
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  firebase_functions_interop: ^1.0.2

dev_dependencies:
  build_runner: ^1.0.0
  build_node_compilers: ^0.2.0